report:
  tableHeaderColor: '#0000FF'
  headerTextColor: '#FFFFFF'
  recordColor: '#000000'
university:
  legal_name: Universidad Rafael Belloso Chacín
  tax_id:
    type: J
    number: 0123456789-1
  address_1: 'Dirección: Av. 16 GUAJIRA, AL LADO DE PLAZA DE TOROS.'
  address_2: Maracaibo, Edo. Zulia, Municipio Juana de Avila.
  address_3: 'Venezuela. Código Postal: 4005'
  phone: 'Teléfonos: +582610000001 / +582610000001'
  email: example@universidad.edu.ve
  logo_path: /images/logo.png
ubication:
  latitude: 10.6941532
  longitude: -71.6343502
  map_zoom: 20
