spring:
  profiles:
    active: postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "*"
      allowed-headers: "*"
