spring:
  profiles:
    active: dev
  config:
    import: classpath:report-config.yml

# Frontend and QR configuration
app:
  frontend:
    base-url: "http://localhost:5173/mobile"
  qr:
    size: 300
