report:
  author: Calmen, Juárez y Vilchez.
  tableHeaderColor: "#0000FF"
  headerTextColor: "#FFFFFF"
  recordColor: "#000000"

university:
  legal_name: Universidad Venezuela
  tax_id:
    type: J
    number: 0123456789-1
  address_1: "Dirección: Av. 16 GUAJIRA, AL LADO DE PLAZA DE TOROS."
  address_2: "Maracaibo, Edo. Zulia, Municipio Juana de Avila."
  address3: "Venezuela. Código Postal: 4005"
  phone: "Teléfonos: +582610000000 / +582610000000"
  email: example@universidad.edu.ve
  logo_path: /images/logo.png
